services:
  php:
    build: .
    container_name: symfony-php-champagnes
    volumes:
      - ./:/var/www/html
      - /var/www/html/var
      - /var/www/html/vendor
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx-champagnes
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: symfony-db-champagnes
    environment:
      POSTGRES_DB: champagnes
      POSTGRES_USER: champagnes_user
      POSTGRES_PASSWORD: champagnes_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-champagnes
    ports:
      - "8080:8080"

volumes:
  pgdata:
